name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Go to project directory
        run: cd D:\a\APinI\APinI
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build APinI
